name: CI Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1.0.0
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1.1.0
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: libs
        path: build/libs
